helpdesk/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from users.views import reset_successful

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('support.urls','support'),namespace='support')),
    path('accounts/',include(('users.urls','users'),namespace='users')),
    path('reset/<uidb64>/<token>/',views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'),name='password_reset_done'),
    path('reset/complete/',views.LoginView.as_view(template_name='users/reset_complete.html'),name='password_reset_complete'),
    
]

support/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('tickets',views.tickets,name='tickets'),
    path('view_ticket/<int:id>',views.view_ticket,name='view_ticket'),
    path('change_ticket_status/<int:id>',views.change_ticket_status,name='change_ticket_status'),
    path('change_ticket_category/<int:id>',views.change_ticket_category,name='change_ticket_category'),
    path('change_ticket_priority/<int:id>',views.change_ticket_priority,name='change_ticket_priority'),
    path('change_ticket_owner/<int:id>',views.change_ticket_owner,name='change_ticket_owner'),
    path('add_ticket_reply/<int:id>',views.add_ticket_reply,name='add_ticket_reply'),
    path('category',views.category,name='category'),
    path('priority',views.priority,name='priority'),
    path('status',views.status,name='status'),
    path('new_category',views.new_category,name='new_category'),
    path('new_priority',views.new_priority,name='new_priority'),
    path('new_status',views.new_status,name='new_status'),
    path('edit_category/<int:id>',views.edit_category,name='edit_category'),
    path('edit_priority/<int:id>',views.edit_priority,name='edit_priority'),
    path('edit_status/<int:id>',views.edit_status,name='edit_status'),
    path('new_ticket',views.client_create_ticket,name='new_ticket'),
    path('new_company',views.new_company,name='new_company'),
    path('my_tickets',views.my_tickets,name='my_tickets'),
    path('create_staffprofile',views.create_staff_profile,name='create_staffprofile'),
    path('new_profile/',views.create_client_profile,name='new_profile2'),
    path('new_profile/<int:id>/',views.create_client_profile,name='new_profile'),
    path('client_companies',views.client_companies,name='client_companies'),
    
]

users/urls.py
from django.urls import path,re_path,include
from django.contrib.auth import views
from . import views as my_views
urlpatterns = [
    
    path('login/',views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('profile/',my_views.my_tickets,name='profile'),
    path('password_reset',views.PasswordResetView.as_view(
        template_name='users/reset_password.html',
        html_email_template_name='users/password_reset_email.html',
        email_template_name='users/email.html',
        subject_template_name='users/subject.txt'
        ),name='password_reset'),
    path('register',my_views.register,name='register'),
    path('users',my_views.users,name='users'),
    path('profile/<int:id>/',my_views.user_profile,name='user_profile'),
    
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser


# Create your models here.
class CustomUserManager( BaseUserManager ):
    def create_user( self,email,password=None ):
        """
        Creates and saves user with the provided email address 
        """
        if not email:
            raise ValueError(  'A proper email address is required' )
        user = self.model(
            email = self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using = self._db)
        return user
    
    def create_superuser( self,email,password ):
        """
        Creates a superuser with a provide username and password
        """
        user = self.create_user(email,password)
        user.is_admin = True
        user.save( using = self._db )
        return user

class CustomUser( AbstractBaseUser ):
    email = models.EmailField(unique=True,max_length=255,verbose_name='Email Address')
    is_active = models.BooleanField(default = True )
    is_staff = models.BooleanField( default = False )
    is_admin = models.BooleanField( default = False)

    objects = CustomUserManager()
    USERNAME_FIELD = 'email' #Users will login with emails
    REQUIRED_FIELDS = []    #Email is required since it is the username field, and pass is always required

    def __str__(self):
        return self.email
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff( self ):
        return self.is_admin

    

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class UserForm ( UserCreationForm ):
    class Meta:
        model = CustomUser
        fields = ['email']

users/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponseRedirect
from .forms import UserForm
from .models import CustomUser
from support.forms import ClientProfileForm
from django.contrib.auth import authenticate,login
from helpdesk.helpers import get_user_profile

# Create your views here.
def my_tickets( request ):
    if( request.user.is_admin ):
        return HttpResponseRedirect(reverse('support:tickets'))
    else:
        return HttpResponseRedirect(reverse('support:my_tickets'))
def register( request ):
    """
    Create a new user
    """
    if request.method != 'POST':
        form = UserForm()
    else:
        form = UserForm( data=request.POST )
        if form.is_valid:
            try:
                new_user = form.save()
                user = authenticate( username=new_user.email,password= request.POST['password1'] )
                login( request,user)
                return HttpResponseRedirect(reverse('support:my_tickets'))
            except ValueError:
                return HttpResponseRedirect(reverse('support:index'))
    context ={'form':form}        
    return render( request,'users/register.html',context )
def users (request):
    users = CustomUser.objects.all()
    profile = get_user_profile( request.user )
    context = { 'users':users, 'profile':profile }
    
    return render( request,'users/users.html',context)

def reset_successful (request):
    return HttpResponseRedirect(reverse('users:login'))


def user_profile(request,id):
    someone = CustomUser.objects.get(id=id )
    userprofile = get_user_profile( someone )
    profile = get_user_profile( request.user )
    #We shall either create or edit a profile
    #We shall only create profiles clients, staff will create their profiles
    if userprofile:
        if request.method != 'POST':
        #Client is creating a new Profile
            form = ClientProfileForm(instance=userprofile)
        else:
            
            form = ClientProfileForm(instance=userprofile,data= request.POST )
            if form.is_valid:
                form.save()
                return HttpResponseRedirect(reverse('users:users'))
    else:
        #Dealing with a new profile
        if request.method != 'POST':
        #Client is creating a new Profile
            form = ClientProfileForm()
        else:
            
            form = ClientProfileForm( request.POST )
            if form.is_valid:
                userprofile = form.save(commit=False)
                userprofile.user = user
                userprofile.save()
                return HttpResponseRedirect(reverse('users:users'))
           
    context = {'form':form,'userprofile':userprofile,'someone':someone,'profile':profile}
    return render(request,'users/create_client_profile.html',context)

    

    
        

users/templates/users/create_client_profile.html
{% extends 'support/index.html' %}
{% load bootstrap4 %}

{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        
            
                <h1>
                    {% if userprofile %}
                    Update Profile
                    {% else %}
                    Create Profile
                    {% endif %}
                </h1>
                
                    <form action="{% url 'support:new_profile' someone.id %}" class="form" method="POST">
                        {% csrf_token %}
                        
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary">
                            <i class="fa fa-save"></i>
                            {% if userprofile %}
                                Update Profile
                            {% else %}
                                Create Profile
                            {% endif %}
                        </button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                
            
        
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>You are {% if userprofile %} updating {% else %} creating {% endif %}profile for {{ someone }}</p>
                
            </div>
        </div>
        
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-pencil"></i>Edit User</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/create_profile.html
{% extends 'support/index.html' %}
{% load bootstrap4 %}

{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form action="{% url 'support:create_staffprofile' %}" class="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend><i class="fa fa-user"></i>Profile</legend>
                        </fieldset>
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary">
                            <i class="fa fa-pencil"></i>
                            {% if profile %}
                                Update Profile
                            {% else %}
                                Create Profile
                            {% endif %}
                        </button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>Update your profile to more information about account</p>
                
            </div>
        </div>
        
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-tools"></i>Reset Password</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} INTERMECH SUPPORT Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
INTERMECH SUPPORT
{% endautoescape %}

users/templates/users/login.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:login' %}"><i class="fa fa-pencil"></i>Register</a></li>
    <li><a href="{% url 'users:password_reset' %}"><i class="fa fa-tools"></i>Reset Password</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form action="{% url 'users:login' %}" class="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend><i class="fa fa-lock"></i>Login</legend>
                        </fieldset>
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i>Login</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-pencil"></i>Register</a>
        </div>
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-tools"></i>Reset Password</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:register' %}"><i class="fa fa-pencil"></i>Register</a></li>
    <li><a href="{% url 'users:password_reset' %}"><i class="fa fa-tools"></i>Reset Password</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form action="{% url 'users:login' %}" class="form" method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i>Login</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-pencil"></i>Register</a>
        </div>
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-tools"></i>Reset Password</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i>Login</a></li>
    <li><a href="{% url 'users:register' %}"><i class="fa fa-pencil"></i>Register</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form  class="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend><i class="fa fa-lock"></i>Reset Password</legend>
                        </fieldset>
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-lock"></i>Reset Password</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:login' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-sign-in"></i>Login</a>
        </div>
        <div class="section">
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-pencil"></i>Register</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} INTERMECH SUPPORT Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
INTERMECH SUPPORT
{% endautoescape %}

users/templates/users/profile.html
{% extends 'support/index.html' %}
{% block content %}
<h1>
    {% if userprofile %}
    Update Profile
    {% else %}
    Create Profile
    {% endif %}
</h1>
{% if profile %}
<table class="table table-striped table-middle-aligned">
    <thead>
        <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Email</th>
            <th scope="col">Company</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
            
            <tr>
                <td>{{ profile.surname }}</td>
                <td>{{ profile.other_name }}</td>
                <td>{{ profile.telephone }}</td>
                <td>{{ profile.user.email }}</td>
                <td>{{ profile.company }}</td>
                <td class="text-right">
                    <div class="item-actions">
                        <a class="btn btn-primary btn-sm" href="#"><i class="fa fa-pencil"></i>Edit</a>
                    </div>
                </td>
            </tr>
            
    </tbody>
</table>
<ul>

            

</ul>

{% else %}
<p>No Profile Yet</p>
{% endif %}
{% endblock %}
{% block actions %}
    <div class="col-md-3" id="sidebar">
                    
        <div class="section">
            <a class="btn btn-lg btn-success btn-block" href="{% url 'support:new_profile' someone.id %}"><i class="fa fa-plus"></i>Create A User Profile</a>
        </div>
                    
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i>Login</a></li>
    <li><a href="{% url 'users:password_reset' %}"><i class="fa fa-tools"></i>Reset Password</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form action="{% url 'users:register' %}" class="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend><i class="fa fa-pencil"></i>Register</legend>
                        </fieldset>
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-pencil"></i>Register</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:login' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-sign-in"></i>Login</a>
        </div>
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-tools"></i>Reset Password</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/reset_complete.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:login' %}"><i class="fa fa-pencil"></i>Register</a></li>
    <li><a href="{% url 'users:password_reset' %}"><i class="fa fa-tools"></i>Reset Password</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
            
        <div class="row">
            <div class="col-md-5">
                    <div class="messages">
                            <div class="alert alert-dismissible alert-success fade-in" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                    <p>Password Reset successful, Login with your new passord</p>
                            </div>
                                
                        </div>
                
                <div class="well">
                    <form action="{% url 'users:login' %}" class="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend><i class="fa fa-lock"></i>Login</legend>
                        </fieldset>
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i>Login</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-pencil"></i>Register</a>
        </div>
        <div class="section">
                <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-tools"></i>Reset Password</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/reset_done.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i>Login</a></li>
    <li><a href="{% url 'users:register' %}"><i class="fa fa-pencil"></i>Register</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        
        
        <div class="row">
            <div class="col-md-5">
                    <div class="messages">
                            <div class="alert alert-dismissible alert-success fade-in" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                
                                    <p>Password Reset Sent</p>
                            </div>
                                
                        </div>
                
                <div class="well">
                    <p>
                        We have emailed you instructions for resetting your password, If an account exists with the email address you entered, you should receive them shortly.</p>
                    <p>    If you don't receive the email, please make sure you entered the correct email and also check your spam folder.
                    </p>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>This is a secured system, please login with your registered email address and passord</p>
                <p>To register or reset passord, use the links above</p>
            </div>
        </div>
        <div class="section">
                <a href="{% url 'users:login' %}" class="btn btn-lg btn-block btn-warning"><i class="fa fa-sign-in"></i>Login</a>
        </div>
        <div class="section">
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-pencil"></i>Register</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/reset_password.html
{% extends 'support/base.html' %}
{% load bootstrap4 %}
{% block navlinks %}
    <li><a href="#"><i class="fa fa-pencil"></i>Register</a></li>
    <li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i>Login</a></li>
{% endblock %}
{% block main%}


<div class="row">
    <div class="col-md-9" id="main">
        <div class="row">
            <div class="col-md-5">
                <div class="well">
                    <form action="{% url 'users:password_reset' %}" class="form" method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button name="submit" class="btn btn-primary"><i class="fa fa-tools"></i>Reset Password</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
            <div class="col-md-7">

            </div>
        </div>
    </div>
    <div class="col-md-3" id="sidebar">
        <div class="section about">
            <div class="well well-lg">
                <p>Type your registered email address,</p>
                <p>We shall you a link to reset your password</p>
            </div>
        </div>
        <div class="section">
                <a href="#" class="btn btn-lg btn-block btn-warning"><i class="fa fa-pencil"></i>Register</a>
        </div>
        <div class="section">
                <a href="{% url 'users:login' %}" class="btn btn-lg btn-block btn-primary"><i class="fa fa-sign-in"></i>Login</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/users.html
{% extends 'support/index.html' %}
{% block content %}
<h1>Users</h1>
{% if users %}
<table class="table table-striped table-middle-aligned">
    <thead>
        <tr>
            <th scope="col">Email Address</th>
            <th scope="col">Staff Account?</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
            {% for someone in users %}
            <tr>
                <td>{{ someone.email }}</td>
                <td><input type="checkbox" checked="{{ someone.is_admin }}" readonly /></td>
                <td class="text-right">
                    <div class="item-actions">
                        <a class="btn btn-primary btn-sm" href="#"><i class="fa fa-pencil"></i>Edit</a>
                        <a class="btn btn-warning btn-sm" href="{% url 'users:user_profile' someone.id %}"><i class="fa fa-user"></i>Profile</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
    </tbody>
</table>
<ul>

            

</ul>

{% else %}
<p>No Users Yet</p>
{% endif %}
{% endblock %}
{% block actions %}
                <div class="col-md-3" id="sidebar">
                    
                    <div class="section">
                        <a class="btn btn-lg btn-success btn-block" href="{% url 'support:new_company' %}"><i class="fa fa-plus"></i>Create A User</a>
                    </div>
                    
                </div>
                {% endblock %}