helpdesk/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from users.views import reset_successful

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('support.urls','support'),namespace='support')),
    path('accounts/',include(('users.urls','users'),namespace='users')),
    path('reset/<uidb64>/<token>/',views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'),name='password_reset_done'),
    path('reset/complete/',views.LoginView.as_view(template_name='users/reset_complete.html'),name='password_reset_complete'),
    
]

support/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('tickets',views.tickets,name='tickets'),
    path('view_ticket/<int:id>',views.view_ticket,name='view_ticket'),
    path('change_ticket_status/<int:id>',views.change_ticket_status,name='change_ticket_status'),
    path('change_ticket_category/<int:id>',views.change_ticket_category,name='change_ticket_category'),
    path('change_ticket_priority/<int:id>',views.change_ticket_priority,name='change_ticket_priority'),
    path('change_ticket_owner/<int:id>',views.change_ticket_owner,name='change_ticket_owner'),
    path('add_ticket_reply/<int:id>',views.add_ticket_reply,name='add_ticket_reply'),
    path('category',views.category,name='category'),
    path('priority',views.priority,name='priority'),
    path('status',views.status,name='status'),
    path('new_category',views.new_category,name='new_category'),
    path('new_priority',views.new_priority,name='new_priority'),
    path('new_status',views.new_status,name='new_status'),
    path('edit_category/<int:id>',views.edit_category,name='edit_category'),
    path('edit_priority/<int:id>',views.edit_priority,name='edit_priority'),
    path('edit_status/<int:id>',views.edit_status,name='edit_status'),
    path('new_ticket',views.client_create_ticket,name='new_ticket'),
    path('new_company',views.new_company,name='new_company'),
    path('my_tickets',views.my_tickets,name='my_tickets'),
    path('create_staffprofile',views.create_staff_profile,name='create_staffprofile'),
    path('new_profile/',views.create_client_profile,name='new_profile2'),
    path('new_profile/<int:id>/',views.create_client_profile,name='new_profile'),
    path('client_companies',views.client_companies,name='client_companies'),
    
]

users/urls.py
from django.urls import path,re_path,include
from django.contrib.auth import views
from . import views as my_views
urlpatterns = [
    
    path('login/',views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('profile/',my_views.my_tickets,name='profile'),
    path('password_reset',views.PasswordResetView.as_view(
        template_name='users/reset_password.html',
        html_email_template_name='users/password_reset_email.html',
        email_template_name='users/email.html',
        subject_template_name='users/subject.txt'
        ),name='password_reset'),
    path('register',my_views.register,name='register'),
    path('users',my_views.users,name='users'),
    path('profile/<int:id>/',my_views.user_profile,name='user_profile'),
    
    
]

support/models.py
from django.db import models
from phone_field import PhoneField
from users.models import CustomUser
import uuid


# Create your models here.
class Category( models.Model ):
    category_name = models.CharField(max_length = 50)
    def __str__(self):
        return self.category_name
    
class Priority ( models.Model ):
    priority = models.CharField(max_length = 50)
    def __str__(self):
        return self.priority
class Status ( models.Model ):
    status = models.CharField(max_length = 50)
    def __str__(self):
        return self.status

class Ticket ( models.Model ):
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length = 500)
    track_id = models.UUIDField(unique=True,default=uuid.uuid4)
    dt = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField()
    client = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='client')
    owner = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='owner')
    assigned_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='assigned_by')

class Reply ( models.Model ):
    ticket = models.ForeignKey( Ticket,on_delete=models.CASCADE )
    message = models.TextField( max_length=500 )
    replier = models.ForeignKey( CustomUser,on_delete=models.CASCADE )
    dt = models.DateTimeField( auto_now_add=True )
class Company ( models.Model ):
    full_name = models.CharField( max_length=200 )
    short_name = models.CharField( max_length=50 )

    def __str__(self):
        return self.short_name

class StaffProfile (models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    surname = models.CharField(max_length=50)
    other_name = models.CharField(max_length=50)
    telephone = PhoneField(help_text='Your Mobile Phone Number')
    def __str__(self):
        return self.surname+' '+self.othername
    

class ClientProfile (models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    surname = models.CharField(max_length=50)
    other_name = models.CharField(max_length=50)
    telephone = PhoneField()
    company = models.ForeignKey( Company,on_delete=models.CASCADE )

    def __str__(self):
        return self.surname+' '+self.other_name

support/forms.py
from django import forms
from .models import Ticket, StaffProfile,Company,ClientProfile,Category,Status,Priority,Reply

class TicketForm( forms.ModelForm ):
    class Meta:
        model = Ticket
        fields = ['subject','priority','category','message']

class StaffProfileForm( forms.ModelForm ):
    class Meta:
        model = StaffProfile
        fields = ['surname','other_name','telephone']
class ClientProfileForm( forms.ModelForm ):
    class Meta:
        model = ClientProfile
        fields = ['surname','other_name','telephone','company']
class CompanyForm( forms.ModelForm ):
    class Meta:
        model = Company 
        fields = '__all__'
class StatusForm( forms.ModelForm ):
    class Meta:
        model = Status 
        fields = '__all__'
class CategoryForm( forms.ModelForm ):
    class Meta:
        model = Category 
        fields = '__all__'
class PriorityForm( forms.ModelForm ):
    class Meta:
        model = Priority 
        fields = '__all__'
class TicketStatusForm( forms.ModelForm ):
    class Meta:
        model = Ticket 
        fields = ['status']
        labels = {'status':'Change Status To:'}
class TicketCategoryForm( forms.ModelForm ):
    class Meta:
        model = Ticket 
        fields = ['category']
        labels = {'category':'Move To Category:'}
class TicketPriorityForm( forms.ModelForm ):
    class Meta:
        model = Ticket 
        fields = ['priority']
        labels = {'priority':'Change Priority To:'}
class TicketOwnerForm( forms.ModelForm ):
    class Meta:
        model = Ticket 
        fields = ['owner']
        labels = {'owner':'Assign To:'}

class ReplyForm( forms.ModelForm ):
    class Meta:
        model = Reply 
        fields = ['message']
        labels = {'message':'Add A Reply'}

support/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .forms import TicketForm,StaffProfileForm,CompanyForm,ClientProfileForm,CategoryForm
from .forms import StatusForm,PriorityForm,TicketStatusForm,TicketCategoryForm,TicketOwnerForm
from .forms import TicketPriorityForm,ReplyForm
from django.contrib.auth.decorators import login_required
from .models import Status,Ticket,StaffProfile,ClientProfile,Company,Category, Priority,Status,Reply
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from users.models import CustomUser
from helpdesk.helpers import get_user_profile


# Create your views here.
def index(request):
    try: 
        profile = StaffProfile.objects.get(user=request.user)
    except:
        profile = None
    finally:
        context = {'profile':profile}    
    return render(request,'support/index.html',context)
@login_required    
def client_create_ticket(request):
    """
    If the client creating the ticket 
    """
    if request.method != 'POST':
        #Client is creating a new ticket
        form = TicketForm()
    else:
        status = Status.objects.get(id=1)
        ip = get_ip_address(request)
        client = request.user
        owner = request.user
        assigned = request.user
        form = TicketForm( request.POST )
        if form.is_valid:
            new_ticket = form.save(commit=False)
            new_ticket.ip = ip
            new_ticket.status = status
            new_ticket.client = client
            new_ticket.owner = owner
            new_ticket.assigned_by = assigned
            new_ticket.save()
            send_ticket_created_email(new_ticket)
            send_ticket_recieved_email(new_ticket)
            return HttpResponseRedirect(reverse('support:my_tickets'))

        pass
    context = {'form':form,'profile':get_user_profile(request)}
    return render(request,'support/create_ticket.html',context)
@login_required
def change_ticket_status(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = TicketStatusForm(instance=ticket,data=request.POST)
    if form.is_valid:
        form.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))
@login_required
def change_ticket(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = TicketCategoryForm(instance=ticket,data=request.POST)
    if form.is_valid:
        form.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))
@login_required
def change_ticket_priority(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = TicketPriorityForm(instance=ticket,data=request.POST)
    if form.is_valid:
        form.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))
@login_required
def change_ticket_owner(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = TicketOwnerForm(instance=ticket,data=request.POST)
    if form.is_valid:
        form.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))
@login_required
def add_ticket_reply(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = ReplyForm(data=request.POST)
    if form.is_valid:
        reply=form.save(commit=False)
        reply.ticket = ticket
        reply.replier = request.user
        reply.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))
@login_required
def change_ticket_category(request,id):
    #method will always be post
    ticket = Ticket.objects.get(id=id)
    form = TicketCategoryForm(instance=ticket,data=request.POST)
    if form.is_valid:
        form.save()
        return HttpResponseRedirect(reverse('support:view_ticket',args=[id]))


@login_required    
def create_staff_profile(request):
    """
    Creating / Editing a user profile 
    """
    #If the use has a profile, we edit that one
    profile = get_user_profile(request.user)
    try:
        userprofile = StaffProfile.objects.get(user = request.user)
    
        #Profile Exists, so we edit
        
        if request.method != 'POST':
        #Client is creating a new Profile
            form = StaffProfileForm(instance=userprofile)
        else:
            user = request.user
            form = StaffProfileForm(instance=userprofile,data= request.POST )
            if form.is_valid:
                form.save()
                return HttpResponseRedirect(reverse('support:tickets'))
    except:
        #Dealing with a new profile
        if request.method != 'POST':
        #Client is creating a new Profile
            form = StaffProfileForm()
        else:
            user = request.user
            form = StaffProfileForm( request.POST )
            if form.is_valid:
                userprofile = form.save(commit=False)
                userprofile.user = user
                userprofile.save()
                return HttpResponseRedirect(reverse('support:tickets'))   
    context = {'form':form,'profile':profile}
    return render(request,'users/create_profile.html',context)

@login_required    
def create_client_profile(request,id):
    """
    Creating / Editing a user profile 
    """
    user = CustomUser.objects.get(id = id)
    userprofile = None
    #If the use has a profile, we edit that one
    try:
        userprofile = ClientProfile.objects.get(user = user)
    
        #Profile Exists, so we edit
        
        if request.method != 'POST':
        #Client is creating a new Profile
            form = ClientProfileForm(instance=userprofile)
        else:
            
            form = ClientProfileForm(instance=userprofile,data= request.POST )
            if form.is_valid:
                form.save()
                return HttpResponseRedirect(reverse('support:tickets'))
    except:
        #Dealing with a new profile
        if request.method != 'POST':
        #Client is creating a new Profile
            form = ClientProfileForm()
        else:
            
            form = ClientProfileForm( request.POST )
            if form.is_valid:
                profile = form.save(commit=False)
                profile.user = user
                profile.save()
                return HttpResponseRedirect(reverse('users:users'))   
    context = {'form':form,'profile':userprofile,'someone':user}
    return render(request,'users/create_client_profile.html',context)

@login_required
def tickets(request):
    tickets = Ticket.objects.all()
    context = { 'tickets':tickets,'profile':get_user_profile(request.user) }
    return render(request,'support/tickets.html',context)
@login_required
def view_ticket(request,id):
    ticket = Ticket.objects.get(id=id)
    profile = get_user_profile(request.user)
    clientprofile = get_user_profile(ticket.client)
    replyform = ReplyForm()
    replies = []
    statusform = TicketStatusForm(instance=ticket)
    categoryform = TicketCategoryForm(instance=ticket)
    ownerform = TicketOwnerForm(instance=ticket)
    priorityform = TicketPriorityForm(instance=ticket)

    try:
        reply = Reply.objects.filter(ticket=id)
        replies.extend(reply)
    except Reply.DoesNotExist:
        pass
            
    context = {
        'ticket':ticket,
        'profile':profile,
        'replies':replies,
        'userprofile':clientprofile,
        'statusform':statusform,
        'categoryform':categoryform,
        'ownerform':ownerform,
        'priorityform':priorityform,
        'replyform':replyform
        }
    return render(request,'support/view_ticket.html',context)

@login_required
def my_tickets(request):
    tickets = Ticket.objects.filter(client=request.user)
    context = { 'tickets':tickets,'profile':get_user_profile(request.user) }
    return render(request,'support/tickets.html',context)
@login_required
def category(request):
    categories = Category.objects.all()
    context = { 'categories':categories,'profile':get_user_profile(request.user) }
    return render(request,'support/category.html',context)
@login_required    
def new_category(request):
    """
    If the client creating the ticket 
    """
    if request.method != 'POST':
        #Client is creating a new ticket
        form = CategoryForm()
    else:
        
        form = CategoryForm( request.POST )
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('support:category'))

        pass
    context = {'form':form,'profile':get_user_profile(request)}
    return render(request,'support/new_category.html',context)

@login_required    
def edit_category(request,id):
    """
    If the client is editing a category 
    """
    category = Category.objects.get(id=id)

    if request.method != 'POST':
        #Client is creating a new ticket
        form = CategoryForm(instance=category)
    else:
        
        form = CategoryForm(instance=category, data=request.POST )
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('support:category'))

        pass
    context = {'form':form,'profile':get_user_profile(request),'category':category}
    return render(request,'support/edit_category.html',context)

@login_required    
def edit_status(request,id):
    """
    If the client is editing a Status 
    """
    status = Status.objects.get(id=id)

    if request.method != 'POST':
        #Client is creating a new ticket
        form = StatusForm(instance=status)
    else:
        
        form = StatusForm(instance=status, data=request.POST )
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('support:status'))

        pass
    context = {'form':form,'profile':get_user_profile(request.user),'status':status}
    return render(request,'support/edit_status.html',context)
@login_required    

support/templates/support/category.html
{% extends 'support/index.html' %}
{% block content %}
<h1>Categories</h1>
{% if categories %}
<table class="table table-striped table-middle-aligned">
    <thead>
        <tr>
            <th scope="col">Category Name</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category }}</td>
                <td class="text-right">
                    <div class="item-actions">
                        <a class="btn btn-primary btn-sm" href="{% url 'support:edit_category' category.id %}"><i class="fa fa-pencil"></i>Edit</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
    </tbody>
</table>
<ul>

            

</ul>

{% else %}
<p>No Tickets Yet</p>
{% endif %}
{% endblock %}

{% block actions %}
                <div class="col-md-3" id="sidebar">
                    
                    <div class="section">
                        <a class="btn btn-lg btn-success btn-block" href="{% url 'support:new_category' %}"><i class="fa fa-plus"></i>Add New Category</a>
                    </div>
                    
                </div>
{% endblock %}

support/templates/support/edit_priority.html
{% extends 'support/index.html' %}
{% load bootstrap4 %}



{% block main %}
    <div class="row">
        <div class="col-md-9" id="main">
            <h1>Edit Priority</h1>
            <form action="{% url 'support:edit_priority' priority.id %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i>Save Priority</button>
                {% endbuttons %}
            </form>
        </div>
        <div class="col-md-3" id="sidebar">
            <div class="well well-lg">
                <p>Enter The Priority Name And Save</p>
            </div>
            <div class="section actions">
                    <a href="{% url 'support:priority' %}" class="btn btn-lg btn-block btn-success"><i class="fa fa-arrow-left"></i>Back To Priorities</a>
            </div>
            <div class="section actions">
                    <a href="#" class="btn btn-lg btn-block btn-danger"><i class="fa fa-trash"></i>Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

support/templates/support/index.html
{% extends 'support/base.html' %}
{% block navlinks %}
    {% if user.is_authenticated %}

        {% if user.is_admin %}
        <li>
            <a href="{% url 'users:users' %}"><i class="fa fa-users"></i>Users</a>
        </li>
        
        <li class="dropdown">
                <a 
                id="settings" 
                href="#" 
                class="dropdown-toggle" 
                data-toggle="dropdown" 
                role="button"
                aria-expanded="false">
                    
                <i class="fa fa-cogs" aria-hidden="true"></i>
                Settings
                <span class="caret"></span>
                
                </a>
                <ul class="dropdown-menu settings" role="menu" aria-labelledby="settings">
                    
                    <li><a href="{% url 'support:category' %}"><i class="fa fa-tag" aria-hidden="true"></i>Categories</a></li>
                    <li class="divider"></li>
                    
                    <li><a href="{% url 'support:priority' %}"><i class="fa fa-tag" aria-hidden="true"></i>Priorities</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'support:status' %}?next=/"><i class="fa fa-tag" aria-hidden="true"></i>Status</a></li>
    
                </ul>
            </li>
            <li>
                    <a href="{% url 'support:client_companies' %}"><i class="fa fa-building"></i>Companies</a>
                </li>
                <li>
                        <a href="{% url 'support:tickets' %}"><i class="fa fa-file"></i>Reports</a>
                    </li>
                <li>
                        <a href="{% url 'support:tickets' %}"><i class="fa fa-ticket"></i>Tickets</a>
                    </li>
                    
        {% endif %}
        
                <li>
                        <a href="{% url 'support:my_tickets' %}"><i class="fa fa-ticket"></i>My Tickets</a>
                    </li>
        <li class="dropdown">
            <a 
            id="user" 
            href="#" 
            class="dropdown-toggle" 
            data-toggle="dropdown" 
            role="button"
            aria-expanded="false">
                {% if profile %}
                Hi {{ profile.other_name }},
                {% else %}
                {{ user }}
                {% endif %}
            <i class="fa fa-user" aria-hidden="true"></i>
            <span class="caret"></span>
            <span class="sr-only">{{ user }}</span>
            
            </a>
            <ul class="dropdown-menu user" role="menu" aria-labelledby="user">
                {% if user.is_admin %}
                <li><a href="{% url 'support:create_staffprofile' %}"><i class="fa fa-edit" aria-hidden="true"></i>Profile</a></li>
                <li class="divider"></li>
                {% endif %}
                <li><a href="{% url 'support:create_staffprofile' %}"><i class="fa fa-lock" aria-hidden="true"></i>Change Password</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'users:logout' %}?next=/"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>

            </ul>
        </li>
    {% else %}
        <li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i>Login</a></li>
        <li><a href="{% url 'users:register' %}"><i class="fa fa-pencil"></i>Register</a></li>
    {% endif %}
    
{% endblock %}
{% block main %}
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col-md-9" id="main">
                    {% block content %}
                    
                    {% endblock %}
                </div>  
                {% block actions %}
                <div class="col-md-3" id="sidebar">
                    
                    <div class="section">
                        <a class="btn btn-lg btn-success btn-block" href="{% url 'support:new_ticket' %}"><i class="fa fa-plus"></i>Create A Ticket</a>
                    </div>
                    
                </div>
                {% endblock %}
            </div>
        {% else %}

            <div class="row align-items-center">
                <div class="col-6 mx-auto col-md-6 order-md-2">
                    
                </div>
                <div class="col-md-6 order-md-1 text-center text-md-left pr-md-5">
                    <h1 class="mb-3 bd-text-purple-bright"> INTERMECH SUPPORT</h1>
                    <p class="lead">
                              Use this tool to report to us any issue that requires our intervention.
                    </p>
                    <p class="lead mb-4">
                              We shall immediately recieve your concern and action it. You can monitor our progress on the raise issue and you can be involved too.
                    </p>
                    <div class="row mx-n2">
                        <div class="col-md-6 px-2">
                            <a href="{% url 'users:login' %}" class="btn  btn-primary btn-lg btn-block w-100 mb-3"><i class="fa fa-sign-in"></i>Login</a>
                        </div>
                        
                        <div class="col-md-6 px-2">
                            <a href="{% url 'users:register' %}" class="btn btn-warning btn-lg btn-block w-100 mb-3"><i class="fa fa-pencil"></i>Register</a>
                        </div>
                        
                    </div>
                    
                </div>
            </div>

        {% endif %}
{% endblock %}

support/templates/support/view_ticket.html
{% extends 'support/index.html' %}
{% load bootstrap4 %}



{% block main %}
    <div class="row">
        <div class="col-md-9" id="main">
            <h1>{{ticket.subject}}</h1>
            <p class="post-metadata">
                <span class="metadata"><i class="fa fa-calendar"></i>{{ticket.dt}}</span>
                <span class="metadata"><i class="fa fa-user"></i>{{ticket.client}}</span>
                {% if userprofile.company %}
                    <span class="metadata"><i class="fa fa-building"></i>{{userprofile.company}}</span>
                {% endif %}
                <span class="metadata"><i class="fa fa-address-card"></i>{{ticket.ip}}</span>
                <span class="metadata"><i class="fa fa-user"></i>{{ticket.owner}}</span>
                <span class="metadata"><i class="fa fa-tag"></i>{{ticket.category}}</span>
                <span class="metadata"><i class="fa fa-battery-three-quarters"></i>{{ticket.status}}</span>
            </p>
            <p>{{ticket.message}}</p>
            <div class="row">
                    <div class="section col-md-3">
                            <form action="{% url 'support:change_ticket_status' ticket.id %}" method="POST">
                                    {% csrf_token %}
                                    {% bootstrap_form statusform %}
                                    {% buttons %}
                                    <button class="btn btn-default btn-block" type="submit"><i class="fa fa-save"></i>Change</button>
                                    {% endbuttons %}
                            </form>
                    </div>
                    <div class="section col-md-3">
                            <form action="{% url 'support:change_ticket_category' ticket.id %}" method="POST">
                                    {% csrf_token %}
                                    {% bootstrap_form categoryform %}
                                    {% buttons %}
                                    <button class="btn btn-default btn-block" type="submit"><i class="fa fa-save"></i>Move</button>
                                    {% endbuttons %}
                            </form>
                    </div>
                    <div class="section col-md-3">
                            <form action="{% url 'support:change_ticket_priority' ticket.id %}" method="POST">
                                    {% csrf_token %}
                                    {% bootstrap_form priorityform %}
                                    {% buttons %}
                                    <button class="btn btn-default btn-block" type="submit"><i class="fa fa-save"></i>Change</button>
                                    {% endbuttons %}
                            </form>
                    </div>
                    <div class="section col-md-3">
                            <form action="{% url 'support:change_ticket_owner' ticket.id %}" method="POST">
                                    {% csrf_token %}
                                    {% bootstrap_form ownerform %}
                                    {% buttons %}
                                    <button class="btn btn-default btn-block" type="submit"><i class="fa fa-save"></i>Assign</button>
                                    {% endbuttons %}
                            </form>
                    </div>
                    
            </div>

            {% if replies %}
            <div class="panel panel-default">
                <div class="panel-heading">Replies</div>
                <div class="panel-body">
                        <div class="list-group">
                                {% for reply in replies %}
                                <li class="list-group-item">
                                    <div class="d-flex w-100 justify-content-between">
                                            <small>{{reply.dt}},<i class="fa fa-user"></i>{{reply.replier}}</small>
                                    </div>
                                    <p class="mb-1">{{ reply.message }}</p>
                                    
                                    <div class="text-right">
                                        <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i>Edit</a>
                                        <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>Delete</a>
                                    </span> 
                                </li>
                                {% endfor %}
            
                        </div>

                </div>
            </div>
            
                
                
            {% endif %}


            <form action="{% url 'support:add_ticket_reply' ticket.id %}" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form replyform %}
                    {% buttons %}
                    <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i>Reply</button>
                    {% endbuttons %}
            </form>
        </div>
        <div class="col-md-3" id="sidebar">
            <div class="section actions">
                <a href="#" class="btn btn-default btn-lg btn-block"><i class="fa fa-print"></i>Print</a>
            </div>
            <div class="section actions">
                    <a href="#" class="btn btn-default btn-lg btn-block"><i class="fa fa-edit"></i>Edit</a>
            </div>
            <div class="section actions">
                    <a href="#" class="btn btn-default btn-lg btn-block"><i class="fa fa-envelope"></i>Resend Email</a>
            </div>
            <div class="section actions">
                    <a href="{% url 'support:tickets' %}" class="btn btn-default btn-lg btn-block"><i class="fa fa-arrow-left"></i>Back To Tickets</a>
            </div>
            <div class="section actions">
                    <a href="{% url 'support:tickets' %}" class="btn btn-default btn-lg btn-block"><i class="fa fa-pencil"></i>Add A Note</a>
            </div>
        </div>
    </div>
{% endblock %}